# Generated by Django 6.0.7 on 2026-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
