# Generated by Django 6.0.7 on 2026-07-18 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0009_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='last_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
