# Generated by Django 6.0.7 on 2026-07-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0010_emailotp_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
