# Generated by Django 6.0.7 on 2026-07-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0011_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
