# Generated by Django 6.0.7 on 2026-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0017_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
