# Generated by Django 6.0.7 on 2026-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0019_product_country_of_origin_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Grocery Store Pvt Ltd', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instruction',
            field=models.CharField(default='Keep Refrigerated', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Pack', max_length=30),
        ),
    ]
