# Generated by Django 6.0.7 on 2026-07-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0020_product_flavour_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('prep_time', models.CharField(default='15 mins', max_length=50)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('calories_per_serving', models.PositiveIntegerField(default=250)),
                ('health_tag', models.CharField(default='Healthy & Fresh', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='carbs_g',
            field=models.DecimalField(decimal_places=1, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_g',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='health_score',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_g',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_note', models.CharField(blank=True, default='1 pack', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogs.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ogs.recipe')),
            ],
        ),
    ]
