# Generated by Django 5.2.17 on 2026-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogs', '0021_recipe_product_calories_product_carbs_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
